### ISSUE TITLE
[FEATURE] Implement option to disable developer news

### ISSUE THREAD

**Issue by MagicAndre1981** [luminous-software/start-page-plus-64-bit#2] opened 2023-04-21 08:01 UTC
**Is your feature request related to a problem? Please describe.**

Add option to disable developer news in StartPage+

**Describe the solution you'd like**

Add option to disable developer news, people who want it back can easily install a [VS2022 compatible version from the market place](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.DeveloperNews2022), for me it only wastes space that I would like to get filled with larger paths from the recent menu.

**Describe alternatives you've considered**

People who want it back can easily install a [VS2022 compatible version from the market place](https://marketplace.visualstudio.com/items?itemName=MadsKristensen.DeveloperNews2022) 

![image](https://user-images.githubusercontent.com/8274816/233578718-0c89a94a-6ba6-4417-b0b9-8e1d221d138c.png)

**Comment by yannduran** [comment] 2023-04-21 13:35
We've had to disagree on this issue in the past. Start Page+ was designed as an all-in-one start page from the very beginning. I do need to update it to cope with multiple feeds though.

I don't remember why, but I have a feeling that the way I designed it, that it won't be a simple fix.

I'm happy to have another look at it though. Apart from not displaying the news items, what did you hope to gain from turning it off?

**Comment by MagicAndre1981** [comment] 2023-04-21 17:49
I want more space for the paths of the solutions in the recent project list. For me the feed is absolutely useless. I'm old RSS subscriber of the MSFT dev blogs in Feedly, so I always read and star feeds there. But users like you may read news in this feed only.

So having an option would satisfy both user types.

**Comment by yannduran** [comment] 2023-04-22 06:56
Thanks for that update. I don't think it's going to be as simple as just hiding the news panel, or else I'd just do it. Don't get me wrong, I'm all for options where it makes sense. However I have two main problems with trying to make this an option.

1. I never intended for any of the panels to be made invisible, so I don't know if the way I've done it would easily allow that to happen without potentially weird gaps from margins that weren't meant to be hidden. That kind of stuff.
2. I can't imagine how it wouldn't look really awkward, to have the whole screen divided into just two panes. Splitting them into anything other than equal halves would also be difficult also.

Anyway I'm happy to have a look at it again, but I have many other things to do first though.

**Comment by MagicAndre1981** [comment] 2023-04-25 13:06
> 1. I never intended for any of the panels to be made invisible, so I don't know if the way I've done it would easily allow that to happen without potentially weird gaps from margins that weren't meant to be hidden. 

You did develop it with option and already expose it in VS options

![image](https://user-images.githubusercontent.com/8274816/234284739-370b1531-1a04-436f-8647-e28b90325e5f.png)

In StartViewModel.cs I only need to add an `if` statement if NewsItemsOptions.Instance.DisplayNewsItems is true or false and this hides it:

![image](https://user-images.githubusercontent.com/8274816/234284540-df7a7ec1-9781-446e-bf75-793e035e39f1.png)

So now it is 50:50, better would be 70:30 (recent projects larger), but I still need to look how this is done (hopefully not in XAML as I hate this).

**Comment by yannduran** [comment] 2023-04-25 13:16
I have a feeling that I added that option for you, but that I never actually got around to implementing it or hiding the option. That's the only thing I can think of that would explain that option being there. I definitely didn't want Start Page+ to have anything other than the 3 panes I designed it to have.

I'd love to see what you've showed in that screenshots with the names of some projects that you have that would require such a wide list, so I can see how the lines/controls are affected.

**Comment by yannduran** [comment] 2023-04-25 13:30
TBH it doesn't look quite as bad as I imagined, just not how I envisaged it.

Yes, it will be in XAML. The control I used specifically divides the space available evenly for its children, so that when the user has changed the width property it will display the panes properly.

**Comment by MagicAndre1981** [comment] 2023-04-25 13:44
I can do a PR draft with the things I already did and allow edits from you so that you play a bit with the size in XAML, so that I can see the place and play on my own until I'm happy with it.

**Comment by yannduran** [comment] 2023-04-25 13:47
Sure, no problem. Just remember what I said before, this will be at the bottom of the issue list. The other issues need to be addressed first.

**Comment by MagicAndre1981** [comment] 2023-05-06 15:17
@yannduran looks like you linked the wrong commit to this issue

**Comment by yannduran** [comment] 2023-05-06 15:20
Linked it where?

**Comment by MagicAndre1981** [comment] 2023-05-06 15:22
> Linked it where?

in [this commit message](https://github.com/luminous-software/start-page-plus-64-bit/commit/12c5a2d635435246c441b3125eec54790a29e00d)

**Comment by yannduran** [comment] 2023-05-06 15:25
Sorry, it's late at night (or early the next morning to be precise). I still can't see where I linked the wrong commit to this issue. Can you be more precise?

**Comment by MagicAndre1981** [comment] 2023-05-06 15:28
this issue is about disabling developer news on startpage not about recent items location in the options dialog. Maybe this happens because you develop it inside a private repository with different issues IDs

**Comment by yannduran** [comment] 2023-05-06 15:34
I do indeed have both a list of **_private_** issues. 

I've finally decided to refer to all issue numbers as `pX#Y` (where `pX` is the private (yannduran) issue number, and `#Y` is the public (luminous-software) issue's number.

I might well have done something wrong somewhere, but I just can't see it from what you've described so far.

**Comment by MagicAndre1981** [comment] 2023-05-06 15:38
Last try with a picture:

![image](https://user-images.githubusercontent.com/8274816/236633618-fcc4af07-41a2-4a49-b250-cad616c001e8.png)

In this commit message you wrote "closes #2" and issue 2 is this issue about diabling developer news, not about location of options. Your internal issue 2 maybe about the settings location.

**Comment by yannduran** [comment] 2023-05-06 15:38
> I can do a PR draft with the things I already did and allow edits from you so that you play a bit with the size in XAML, so that I can see the place and play on my own until I'm happy with it.

I've slotted this issue into the v0.23 sprint (visible as a milestone), the one AFTER the next sprint (v0.22), but if you want to organise that pull request, I'm happy to have a look at what you've done. If it turns out to be easy I'll bump it into the v0.22 sprint.

**Comment by yannduran** [comment] 2023-05-06 15:45
if you see [bug] or [feature] prefixes to bug issues, that mean I found it myself & am probably not going to bother creating a public issue for it. It'll just be mentioned in the changelist & the release text. Uppercase ones are from the public, and I just my public issue for it. I hope I'm making sense at this hour.

The same

**Comment by yannduran** [comment] 2023-05-06 15:47
> if you see [bug] or [feature] prefixes to bug issues, that mean I found it myself & am probably not going to bother creating a public issue for it. It'll just be mentioned in the changelist & the release text. Uppercase ones are from the public, and I just my public issue for it. I hope I'm making sense at this hour.
> 
I've been sorting out my process. Yes #2 was my private issue, and you should never have seen a 'closes #2', that should only ever have appeared  in my private issue.

Thanks for bringing it up though@!

**Comment by MagicAndre1981** [comment] 2023-05-06 15:48
but the "closes #" was the cause. Now github closes the linked issue, but this issue about disabling developer news is still not implemented.

**Comment by MagicAndre1981** [comment] 2023-05-06 15:50
> I've been sorting out my process. Yes #2 was my private issue, and you should never have seen a 'closes #2', that should only ever have appeared in my private issue.

ok, this explains it. Good night

**Comment by yannduran** [comment] 2023-05-06 15:51
I wondered how that got closed, because I didn't intentionally close it. And now you've explained how that happened.

Something like that shouldn't happen again, but please let me know if you see something!

**Comment by yannduran** [comment] 2023-05-06 15:51
Good night!

**Comment by MagicAndre1981** [comment] 2023-05-07 21:12
> but if you want to organise that pull request, I'm happy to have a look at what you've done. If it turns out to be easy I'll bump it into the v0.22 sprint.

it is very easy. I opened #32 as draft. Now I need to know how to change the layout from 50%:50% to 70%:30% to give recent solutions more space.

**Closed as completed** 2023-06-04 06:13 UTC
Labels: enhancement
