### ISSUE TITLE
[BUG] NullReferenceException in LoadAsync()

### ISSUE THREAD

**Issue by MagicAndre1981** [luminous-software/start-page-plus-64-bit#1] opened 2023-04-21 07:51 UTC
**Describe the bug**

I get a NullReferenceException in [LoadAsync()](https://github.com/luminous-software/start-page-plus-64-bit/blob/eb79537e79a146d6564bf279bc6fe25eb672e578/src/vsix/UI/Services/RecentItems/MruPrivateSettingsService.cs#L195)

**To Reproduce**

clone code and debug the extension in Exp-Instance and because I haven't debuged anything before in Exp instance, my MRU list is empty which likely triggers this bug.

**Expected behavior**

no exception

**Screenshots**

![image](https://user-images.githubusercontent.com/8274816/233575230-21c24d6f-3cc0-47f6-9d28-f36e48090904.png)

But after clicking a messagebox about the NullReferenceExcepetion happened I now see the StartPage 😍 🥳 🙌 :

![image](https://user-images.githubusercontent.com/8274816/233576903-2576cb10-3372-4dee-a24a-1303002ef755.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 11 22621.x
 - Version [e.g. 22] VS 2022 17.4 LTSC 

**Smartphone (please complete the following information):**

**Comment by yannduran** [comment] 2023-04-21 13:28
Thanks André! It looks like I've brought in a regression bug. I remember fixing this before. Easy one.

**Comment by yannduran** [comment] 2023-04-27 05:49
Fixed in v0.20

**Closed as completed** 2023-04-27 05:50 UTC
Labels: bug
